version: "3.8"
services:
  postgres:
    image: postgres:14
    container_name: bug-free-adventure-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bug-free-adventure
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
